node_id: node-5
bind_address: 0.0.0.0
advertise_addr: node5:7005
node_port: 7005
seed_peers:
  - node1:7001
  - node2:7002
  - node3:7003
  - node4:7004
  - node6:7006
gossip_interval_ms: 1000
fanout: 3
membership_timeout_ms: 5000
enabled_aggregations:
  - sum
  - average
  - min
  - max
aggregation: average
initial_value: 90
log_level: info
